---
title: "API Test"
author: "Bobby Nelson"
date: "2/24/2022"
output: html_document
---

```{r}
library(tidyverse)
library(htmltools)
library(httr)
library(xml2)
library(leaflet)
library(sf)
library(sfheaders)
library(jsonlite)
library(lubridate)
library(scales)
library(plotly)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# API call

```{r}
# api key
key <- readChar("BusTracker/api_key.txt", file.info("BusTracker/api_key.txt")$size)

# base url for the api calls
base_url <- "http://realtime.portauthority.org/bustime/api/v3"
```

```{r}
# function to query vehicle data from api
# following from: https://urbandatapalette.com/post/2021-03-xml-dataframe-r/
getBusData <- function(value, type) {
    # don't send request if more than 10 values because of api limit
    if (length(value) > 10) {
        stop("Error, too many values to search.")
    }
    
    # add key to request
    url <- paste0(base_url, "/getvehicles?key=", key)
    
    # add either route or vehicle id to request
    if (type == "route") {
        url <- paste0(url, "&rt=", paste0(value, collapse=","))
    } else if (type == "vid") {
        url <- paste0(url, "&vid=", paste0(value, collapse=","))
    } else {
        stop("Error, request type not recognized.")
    }
    request <- RETRY("GET", URLencode(url), repeated=TRUE)
    content <- content(request, "text")
    
    # parse xml
    xml <- as_list(read_xml(content))
    
    bustime_df <- as_tibble(xml) %>%
        unnest_wider(`bustime-response`) %>%
        unnest(cols = names(.)) %>%
        readr::type_convert() 
}

c <- getBusData(c("15"), type="route")
```

```{r}
getRouteData <- function() {
    # add key to request
    url <- paste0(base_url, "/getroutes?key=", key)
    
    request <- RETRY("GET", URLencode(url), repeated=TRUE)
    content <- content(request, "text")
    
    # parse xml
    xml <- as_list(read_xml(content))
    
    bustime_df <- as_tibble(xml) %>%
        unnest_wider(`bustime-response`) %>%
        unnest(cols = names(.)) %>%
        readr::type_convert() %>%
        # remove non-bus info
        filter(rtpidatafeed == "Port Authority Bus")
}
route.data <- getRouteData()
```

# Generate static data

## Generate Bus Stop List

```{r}
stop_spdf <- st_read("../PAAC_Stops_1909.shp")
```

```{r}
stop_spdf <- stop_spdf %>%
  filter(Mode == "Bus")
```

```{r}
#st_write(stop_spdf, "BusTracker/data/bus_stops.shp")
```

# Pattern Data

```{r}
# get route patterns
getPatternData <- function(route) {
  # add key to request
  url <- paste0(base_url, "/getpatterns?key=", key)
  
  # request patterns for the route
  url <- paste0(url, "&rt=", route)
  url <- paste0(url, "&rtpidatafeed=Port%20Authority%20Bus&format=json")
  

  request <- RETRY("GET", URLencode(url), repeated=TRUE)
  content <- content(request, "text")
  results <- fromJSON(content)
  
  return(results$`bustime-response`$ptr$pt[[1]])
}
```

```{r}
url <- paste0(base_url, "/getpatterns?key=", key)
    
# request patterns for the route
url <- paste0(url, "&rt=", "15")
url <- paste0(url, "&rtpidatafeed=Port%20Authority%20Bus&format=json")
```

```{r}
request <- RETRY("GET", URLencode(url), repeated=TRUE)
content <- content(request, "text")
results <- fromJSON(content)
```

```{r}
p1 <- results$`bustime-response`$ptr$pt[[1]]
p2 <- results$`bustime-response`$ptr$pt[[2]]
```

```{r}
polygon <- p1 %>%
  st_as_sf(coords=c("lon", "lat")) %>%
  st_convex_hull()

ggplot(polygon) + 
  geom_sf()
```

```{r}
p3 <- rbind(p1, p2)
```


```{r}
leaflet() %>%
  addProviderTiles("OpenStreetMap.HOT") %>%
  setView(-79.9959, 40.4406, 10) %>%
  addLayersControl(overlayGroups=c("Stops", "Buses", "Routes")) %>%
  addPolylines(data=getPatternData("1"),
               group="Routes",
               fill=FALSE,
               color="green",
               lat=~lat,
               lng=~lon)
```
## Get predictions

```{r}
url <- paste0(base_url, "/getpredictions?key=", key)
    
# request patterns for the route
url <- paste0(url, "&vid=", "6011")
url <- paste0(url, "&rtpidatafeed=Port%20Authority%20Bus&format=json")
request <- RETRY("GET", URLencode(url), repeated=TRUE)
content <- content(request, "text")
results <- fromJSON(content)
p1 <- results$`bustime-response`$prd
```

```{r}
# get bus predictions
getPredictionData <- function(value, type) {
  # add key to request
  url <- paste0(base_url, "/getpredictions?key=", key)
  
  # vid or stop prediction
  if (type == "vid") {
    url <- paste0(url, "&vid=")
  } else if (type == "stpid") {
    url <- paste0(url, "&stpid=")
  } else {
    return()
  }
  
  # request patterns for the route
  url <- paste0(url, value)
  url <- paste0(url, "&rtpidatafeed=Port%20Authority%20Bus&format=json")
  

  request <- RETRY("GET", URLencode(url), repeated=TRUE)
  content <- content(request, "text")
  results <- fromJSON(content)
  
  return(results$`bustime-response`$prd)
}
pred <- getPredictionData("6011", type="vid")
```

```{r}
# https://stackoverflow.com/a/43626186
c_trans <- function(a, b, breaks = b$breaks, format = b$format) {
  a <- as.trans(a)
  b <- as.trans(b)

  name <- paste(a$name, b$name, sep = "-")

  trans <- function(x) a$trans(b$trans(x))
  inv <- function(x) b$inverse(a$inverse(x))

  trans_new(name, trans, inverse = inv, breaks = breaks, format=format)
}
rev_date <- c_trans("reverse", "time")


plot <- pred %>%
  mutate(stpnm = as.factor(stpnm),
         prdtm = parse_date_time(prdtm, "%Y%m%d %h:%M"),
         hour.minute = paste0(hour(prdtm), ":", minute(prdtm))) %>%
  arrange(prdtm) %>%
  mutate(stpnm = factor(stpnm, unique(stpnm))) %>%
  head(5) %>%
  ggplot(aes(y=stpnm,
             x=vid)) +
  geom_point(aes(color=stpnm), size=2, shape="square") +
  geom_text(aes(label=hour.minute), nudge_x=0.25, size=3, hjust=0) +
  #scale_y_continuous(trans = rev_date) +
  theme_minimal() +
  theme(panel.grid.major.x = element_line(linetype="solid", color="black",
                                          arrow=grid::arrow(length=unit(0.3, "cm"),
                                                                        ends="first",
                                                                        type="closed")),
        axis.ticks.x=element_blank(),
        axis.text.x=element_blank(),
        legend.position="none") +
  ylab("") +
  xlab("")
plot
#ggplotly(plot)
```

# Stop information

```{r}
stop_spdf <- st_read("BusTracker/data/bus_stops.shp")
```

```{r}
stop_spdf <- stop_spdf %>%
  filter(Mode == "Bus")
```


```{r}
stp.pred <- getPredictionData("3137", type="stpid")
```

```{r}
pat <- getPatternData("1")
```

```{r}
p <- pat %>%
  st_as_sf(coords=c("lon", "lat")) %>%
  summarise(geometry = st_combine(geometry)) %>%
  st_cast("MULTILINESTRING")
```

```{r}
ggplot(p) +
  geom_sf(fill=NA)
```


